jhalter/mobius

hotline/flattened_file_object.go, hotline/flattened_file_object_test.go
This fixes a bug that happens when an uploaded file contains a file comment.  The bug happens because the comment byte length was not included when calculating the length of the information header, causing the comment bytes to be appendedto the file.
=> Fix file corruption bug for commented files

hotline/flattened_file_object.go, hotline/flattened_file_object_test.go, hotline/time.go, hotline/transaction_handlers_test.go
This replaces hardcoded placeholder create/modify timestamps with the real times, mostly.  Create time is OS specific, so for now I'm ignoring it and using the modify time as a stand-in.
=> Add partial support for file create/modify timestamps

hotline/client_conn.go, hotline/server.go, hotline/transaction_handlers.go, hotline/transaction_handlers_test.go
Squashed bugs:
* A v1.8+ user that has connected but not agreed will show up in chat and the userlist as a blank user name
* Race condition where a v1.8+ user in connected but not agreed state duplicated the ID of the next user to connect
* A v1.8+ user that is connected but not agreed will receive the user list
=> Fix multiple issues with v1.8+ login sequence

README.md
Added both light and dark versions of the Mobius logo at the beginning of the read me.  These should change depending on the system theme (MacOS appearance Light/Dark for example) as per Github docs: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
=> Updated README.md to include Mobius logo(s)

cmd/mobius-hotline-server/main.go
Addresses #38 where configs had to have a trailing slash. Server will now add a trailing slash if it is not present. I also add a slash to the end of the default config directory for Windows so that it is consistent with the other OSes.
=> Mobius 38 - improve config dir flag.

hotline/ban.go, hotline/field.go, hotline/server.go, hotline/transaction_handlers.go
It's unlikely this feature will see much use, but in the interest of having full feature parity with the official software and in having a way to somewhat mitigate any bad actors, I've implemented temporary and permanent user banning by client IP.  Also it was fun!
Temp bans are 30 minutes to match the official software behavior.
Example `Banlist.yaml`, where IP is banned until time.  A nil time indicates permanent ban.
```
192.168.86.31: 2022-06-24T16:37:00.755689-07:00
192.168.86.32: nil
```
Fixes #28
=> Implement user ban

hotline/access.go, hotline/field.go, hotline/server.go, hotline/transaction_handlers.go, hotline/transaction_handlers_test.go
This implements the "Can use any name" permission.  If this permission is disabled, the client username is forced to match the username of the account.
Fixes #2
=> Implement "Can use any name" permission

cmd/mobius-hotline-server/mobius/config/config.yaml, hotline/config.go, hotline/files.go, hotline/transaction_handlers.go
This adds a new config file option named "IgnoreFiles" with the following defaults:
```
IgnoreFiles:
- '^\.*'     # Ignore all files starting with ".".  Leave this set if you are using the PreserveResourceForks option.
- '^@'       # Ignore all files starting with "@"
```
Users can add arbitrary new regex patterns if they wish.
Fixes #44
=> Add config option to specify ignored filename patterns

hotline/news.go, hotline/server.go, hotline/transaction_handlers.go, hotline/transaction_handlers_test.go
This implements access controls for HandleDelNewsItem, which is called when a threaded news client issues a delete for a Category or Bundle.
=> Implement access controls for threaded news item deletion

hotline/access.go
It seems that the SendPrivMsg access is set by bit 40 rather than what is in the 1.9 protocol documentation, bit 19. 
Fixed.
=> Fix accessSendPrivMsg permission

hotline/client.go, hotline/transaction.go
Add display of error messages sent from server to client, which fixes a client crash that happens when if the client tries to view a Drop Box without the necessary permission.  This is a starting point for further error response handling/display.
=> Add error message handling to client

cmd/mobius-hotline-server/main.go, hotline/server.go, hotline/stats.go
This adds basic stat counters equivalent to the Hotline Server 1.9.2 stats:
The Mobius stat counters are available when the server is run with the optional `--stats-port` command line argument.
Example output when the server is run with: `--stats-port=5603`:
``` 
curl -s localhost:5603 | jq .           
{
"CurrentlyConnected": 0,
"DownloadsInProgress": 0,
"UploadsInProgress": 0,
"WaitingDownloads": 0,
"ConnectionPeak": 0,
"ConnectionCounter": 0,
"DownloadCounter": 0,
"UploadCounter": 0,
"Since": "2022-07-04T14:18:27.473286-07:00"
}
```
Note: WaitingDownloads is currently unimplemented (#61)
Related to #29
=> Add basic stat counters

cmd/mobius-hotline-server/mobius/config/config.yaml
Update the default config to register with trackers from the Gloarbline 1.9.7 client that are still active.
=> Register with Gloarbline 1.9.7 client default trackers

hotline/server.go, hotline/transaction_handlers.go, hotline/transaction_handlers_test.go
This change fixes two Frogblast compatibility issues:
1. Frogblast does not seem to follow the HL 1.5+ login/agreement flow, so I've made clients identifying as version `0xb9` go down the 1.2.3 path instead.  
2. Frogblast sends a ChatID field value of `00 00 00 00` for public chat, which seems unique to this client.  I'd added a check for this.
Tested in OS X 10.4 running in Qemu.
Fixes #72
=> Improve Frogblast client compatibility

hotline/server.go
This fixes issue that was causing the memory containing the client login info to be overwritten with chunks of chat message data.  This was happening because scanner.Bytes() returns a byte slice that is re-used for subsequent writes, so we need to make a copy of the data.
Fixes #75
=> Fix overwrite of user info due to buffer re-use

hotline/client_conn.go, hotline/transaction_handlers_test.go
Fix compatibility with [gtkhx](https://gtkhx.sourceforge.net/).  
Most clients do not care if the Type field is set in transaction replies, but the GtkHx client does not tolerate this at all.  The official Hotline server leaves the type as 00 00 for replies, so in this change I am making the Mobius behavior consistent with the official release software which has the effect of fixing the GtkHx issues.
Fixes #78
=> Fix GtkHx compatability

hotline/client.go, hotline/ui.go
This adds an optional user setting to trigger the terminal bell on receipt of a chat message
=> Add option to trigger terminal bell for chat messages

hotline/server.go
This appears to fix issue #84 for the Obsession client.  The fix was to add it to the growing list of known clients that use the old 1.2.3 login behavior instead of the 1.5+ behavior.  
I need to revisit and figure out a better solution -- maybe flip this around and assume that all clients use 1.2.3 behavior unless a known 1.5+ version is provided.
Tested with Obsession Hotline Client 109.2
=> Improve compatibility with Obsession client

hotline/news.go, hotline/server.go, hotline/transaction_handlers.go, hotline/transaction_handlers_test.go, hotline/util.go, hotline/util_test.go
1. Fix handling of article IDs sent as 4 bytes instead of 2
2. Fix incorrect article count listing that strangely only affects third party clients
Related #87
=> Fix threaded news bugs

hotline/transaction_handlers.go
This fixes a bug introduced in 0.10.15 where threaded news replies are not correctly threaded under the parent news post
=> Fix bug in news article reply threading

hotline/tracker.go, hotline/tracker_test.go, hotline/ui.go
Handle errors when fetching servers from the tracker list and present and error modal instead of panicking:
Fixes #102
=> Handle tracker list errors

hotline/file_path.go
Fix scanner buffer re-use for fileItemScanner
=> Fix scanner buffer re-use for fileItemScanner

hotline/ui.go
This fixes an issue where the client would connect to the incorrect server when joining from the tracker listing.
=> Fix bug in client tracker list

.gitignore, Dockerfile, docker-compose.yml
Hi there!
Thank you so much for creating Mobius! I'm setting up my own instances and made some contributions that I hope you find useful. Among them are:
- Not running /app/server as root. With Docker, root in the container has the same privileges as root on the host which is a security risk.
- Added a docker-compose.yml file for easier building/deployment
- Updated the .gitignore file to ignore the config directory which can be bind mounted.
Please let me know if you would like to see any changes to this to make this PR acceptable. Thanks again!
=> No run as root

docker-compose.yml
One more. After running `docker compose up -d` the container will be active again after a host reboot.
=> Making it so the container restarts on host reboot

cmd/mobius-hotline-server/main.go, hotline/server.go
Add command line flag to specify which network interface to listen on.  The `net.Listen` function wants this to be a string of an IP address on an interface of the host.
Example usage to listen on the interface with IP 169.254.87.101 bound and port 5600
`--interface=169.254.87.101 --bind=5600`
I'd maybe like to rename `--bind` now, but will avoid making a breaking change for now.
#116
=> Add cmdline flag to specify network interface

hotline/file_path.go, hotline/files.go, hotline/server.go, hotline/transaction_handlers.go
Add support for [Mac Roman](https://en.wikipedia.org/wiki/Mac_OS_Roman) character encoding.  
Incoming strings from the client will be assumed to be Mac Roman encoding instead of ASCII and converted to UTF-8.
Outgoing strings will be converted from UTF-8 to Mac Roman.
Mac Client:
Server file system:
```
❯ ls
HéLLø                   My Cool Stuff ƒ
```
=> Add support for Mac Roman character encoding

hotline/files.go
Fix handling of symlinks in Files dir.  Removed unnecessary filepath.Join that was breaking the path.
=> Fix handling of symlinks in Files dir

hotline/transaction_handlers.go, hotline/transaction_handlers_test.go
* Don't send comment field if comment is not present
* Don't send file size field for folders
=> Make GetFileInfo behavior consistent with official 1.9 server behavior

cmd/mobius-hotline-server/main.go
This was the only change I needed to make in order to hit the ground running with a Hotline server on NetBSD. I'll admit that I haven't validated every code path to ensure NetBSD makes a fully-featured Mobius host, but I was able to get from zero to 60 with nothing but this.
Given just how much functionality this change has enabled in my testing, I kinda expect it would also enable FreeBSD, OpenBSD, DragonFly and perhaps every other platform supported by Go to Just Work, too.
=> If no predefined default path for server config, look in the current dir

hotline/files.go
Ignore files with incompatible names that cannot be translated to Mac OS Roman encoding instead of completely failing the "Get File List" transaction.
=> Ignore files with incompatible names

hotline/file_wrapper.go
This fixes a bug that happens when:
1. Optional "Enable Resource Forks" feature is true
2. A file comment is added
3. The comment is updated to be shorter than the original
The expected behavior is that the hidden .info file is replaced with the new data, but this wasn't happening because the file flag was not set to truncate on write.
=> Fix corrupt file info forks

Dockerfile, README.md
This reverts the Dockerfile change in #111 to run the server as a non-root user by default, for two reasons:
1) Most users of the Docker image do not build the image themselves from the Dockerfile, so including a hardcoded UID/GID in the Docker image means they will always have to pass the `--user` flag to override the hardcoded user to something specific to their system, or else open up file permissions.  This came up in #124.  
2) Using the debian-stable image to run the adduser command increases the image size by >10x.
As an alternative, I've updated the README doc with a recommendation to run the image with the --user flag.
=> Remove hardcoded user from Dockerfile

README.md, cmd/mobius-hotline-server/main.go, hotline/server.go, internal/mobius/api.go
This replaces the `--stat-port` flag and HTTP endpoint with a new `--api-addr` flag, with a couple of additional administrative endpoints to provide functionality  present in the original Hotline server UI but missing in Mobius.
* `POST /api/v1/shutdown - sends message to connected clients and shuts down the server`
* `GET /api/v1/reload- reloads the configuration files from disk`
* `GET /api/v1/stats` - returns server runtime statistics and counters.
Fixes #4
=> Add initial HTTP API endpoints

hotline/account.go, hotline/client_conn.go, hotline/file_transfer.go, hotline/server.go, hotline/server_test.go, internal/mobius/transaction_handlers.go, internal/mobius/transaction_handlers_test.go
The official Hotline Server has a feature to override the files that a user account sees by putting a folder or alias called "Files" in the user account directory.
To provide equivalent functionality in Mobius, this change adds support for an optional FileRoot in the user account yaml files under  `config/Users/*`
Example: 
```
FileRoot: /foo/bar/baz
```
Fixes #30
=> Implement “Customized files for users” feature

cmd/mobius-hotline-server/mobius/config/Users/admin.yaml, cmd/mobius-hotline-server/mobius/config/Users/guest.yaml, hotline/access.go, hotline/account.go, internal/mobius/account_manager.go, internal/mobius/account_manager_test.go, internal/mobius/test/config/Users/admin.yaml, internal/mobius/test/config/Users/guest.yaml, internal/mobius/test/config/Users/user-with-old-access-format.yaml, internal/mobius/transaction_handlers.go, internal/mobius/transaction_handlers_test.go
The account config files in config/Users were not originally intended to be viewed and edited by humans, but in practice it's useful to see and edit permissions outside of a Hotline client.
This change overrides the YAML marshal/unmarshaling to write the account permission bitmap as a human readable map of boolean flags instead of the previously inscrutable array of ints.
Existing user configs in the old format can still be read and will update to the new format on first save. 
I also realized the Folder Upload/Download access bits missing and fixed them.  
```
Access: [96, 112, 12, 32, 3, 128, 0, 0]
```
```
Access:
DownloadFile: true
DownloadFolder: true
UploadFile: true
UploadFolder: false
DeleteFile: false
...
```
=> Improve human readability of account config files

hotline/server.go
There's a log in the folder upload that breaks if the server sends a 16-bit integer.
This PR keeps the existing logging functionality, but uses a different parsing strategy.
=> Account for 16 vs 32 bit integers in folder upload
