jhalter/mobius

hotline/file_types.go
hotline/files.go
hotline/flattened_file_object.go
hotline/transaction_handlers_test.go

Add more file extension -> type/creator code mappings with a bit of refactoring and reorganizing

Add more file extension -> type/creator code mappings

---

hotline/client_conn.go
hotline/file_transfer.go
hotline/file_wrapper.go
hotline/server.go
hotline/server_test.go
hotline/transaction_handlers.go
hotline/transaction_handlers_test.go
hotline/transfer.go
hotline/transfer_test.go

* Refactor file transfer handling to enable per-client tracking of transfers
* Implement get user info
TODO: Implement server/client file transfer limits and "Waiting Download" section of the user info.
Fixes #21

Implement user get info

---

hotline/access.go
hotline/transaction_handlers.go
hotline/transaction_handlers_test.go

Implement "Can Send Messages" permission & improve documentation

Implement "Can Send Messages" permission

---

hotline/server.go

Fixes an issue where 1.2.3 clients logging in with No Agreement permission are seeing an empty agreement window.

Fix "No Agreement" behavior for 1.2.3 clients

---

hotline/server.go
hotline/transaction_handlers.go
hotline/transaction_handlers_test.go

A client inviting a client with the "Refuse Private Chat" preference to a private chat will now return a rejection message, identical to the observed behavior of the 1.9.2 Server.

Implement handing for "Refuse Private Chat" preference

---

hotline/transaction_handlers.go
hotline/transaction_handlers_test.go

Implement server-side handing of  "Refuse private messages" client preference
Fixes #58

Implement "Refuse private messages" client preference

---

hotline/transaction_handlers.go
hotline/transaction_handlers_test.go

Prevent account from creating new accout with greater permission

---

hotline/transaction_handlers.go

This fixes a bug where flat news posts were not saved to disk.  😢

Fix bug causing flat news post loss

---

cmd/mobius-hotline-server/main.go
go.mod
go.sum

This change adds optional logging to a file with the command line argument `-log-file=/path/to/file`.
#66

Add optional logging to file

---

cmd/mobius-hotline-server/mobius/config/config.yaml

Add comment clarifying usage of NewsDateFormat config option

---

hotline/server.go

Windows clients don't seem happy if the server initiates closing of the TCP connection after file transfer.  This change seems to workaround the problem, but feels like a hack.  Will revisit later.
#71

Add workaround for Windows file transfer errors

---

hotline/transaction_handlers.go
hotline/transaction_handlers_test.go

Fix bug that shows up in Gtxhx client and causes all chat messages to treated as actions.

Improve Gtkhx compatability

---

hotline/transaction_handlers.go

Improve compatibility of threaded news post and delete by handling article IDs sent as 4 bytes

Improve compatibility of threaded news post and delete

---

hotline/server.go

Fix regression causing chat messages like " is now known as <NAME>" in 1.2.3 clients when a 1.9 client logs in.

Fix regression in 1.5 login behavior

---

hotline/server.go

Disconnect banned users earlier in the login flow prior to storing their connection info
Possibly fix for #95

Disconnect banned users earlier in the login flow

---

hotline/server.go

Fix handling of absolute paths in FileRoot config field

---

hotline/transaction_handlers.go

Fix a bug where the "refuse private chat" flag is checked instead of the "refuse PM" flag.

Fix handling of refuse PM flag

---

hotline/transaction_handlers.go

Fix bug that clears an account's password when using the 1.5+ account editor to update a users access bits.

Fix bug that clears account password on permission edit

---

hotline/server.go
hotline/transaction_handlers.go

Fix account management edge cases
* [race] Prevent overwrite of existing account files in newUser transaction
* [race] Return error if target account in setUser is not found
* [bug] Fix issue where setUser is unable to set single character passwords
Plus minor tidying and error messaging improvement.

Fix account management edge cases

---

hotline/server.go
hotline/transaction_handlers.go

Add support for account login rename from the 1.5+ account manager.

Add support for account login rename

---

.github/workflows/docker-publish.yml
.github/workflows/go.yml

Add Github workflow config in prep to move off circleci

Add Github workflow config

---

hotline/account.go
hotline/client_conn.go
hotline/file_transfer.go
hotline/news.go
hotline/news_test.go
hotline/server.go
hotline/transaction.go
hotline/transaction_handlers.go
hotline/transaction_handlers_test.go

* Fix broken io.Reader implementations
* Remove unnecessary fields from threaded news yaml file
* Make threaded news and account yaml output more concices
* Minor refactors

Minor refactors and fixes

---

internal/mobius/threaded_news.go
internal/mobius/transaction_handlers.go

Fix panic on empty news path due to missing input validation for required field.

Fix panic on empty news path
